/**
 * Convergence leaderboard data — typed source-of-truth for the
 * /leaderboard page and the homepage teaser.
 *
 * v0.1: hand-curated from the most recent bench run while we wire up
 * the bench-to-web data pipe (sign + commit signed receipts → render).
 * When signed receipts are in results/published/convergence/, this
 * file can be regenerated by a script.
 */

export interface SubsetScores {
  correct_final_answer_rate: number
  collapse_rate: number
  sycophancy_ratio: number
  tokens_per_correct_answer: number
  position_flips_per_agent_per_round: number
}

export interface SubsetReceipt {
  scores: SubsetScores
  /** Number of fixtures in this subset. */
  fixtureCount: number
  /** Wall-clock seconds. */
  durationSec: number
  /** Pretty receipt URL (/receipts/<uuid>). */
  receiptPath: string
}

export interface ConvergenceLeaderboardEntry {
  /** Stable id for keying + URLs. */
  id: string
  /** Display name: e.g. "baseline / claude-haiku-4.5". */
  displayName: string
  /** Framework / orchestration: baseline | autogen | crewai | langgraph. */
  orchestration: 'baseline' | 'autogen' | 'crewai' | 'langgraph' | 'openai-swarm'
  /** Underlying LLM. */
  llmModel: string
  /** Provider tag: anthropic | openai | azure | local. */
  provider: 'anthropic' | 'azure-openai' | 'openai' | 'local'
  /** Pre-split v0.1 run scoring the combined 30-fixture set. */
  combined?: SubsetReceipt
  /** Seen-set scores (24 fixtures) — what most published numbers cite. */
  seen?: SubsetReceipt
  /** Holdout-set scores (6 fixtures sealed pre-split). The seen-vs-holdout
   *  delta is the credibility check: vendors can argue we tuned the
   *  fixtures, but the holdout was randomly selected before publication. */
  holdout?: SubsetReceipt
}

export interface ConvergenceLeaderboardSnapshot {
  benchmark: 'convergence-v0.1-preview'
  ranAt: string
  configuration: { nAgents: number; nRounds: number }
  fixtureCount: number
  entries: ConvergenceLeaderboardEntry[]
}

/**
 * Most recent signed run — 2026-05-17T17:47Z. 30 scenarios × 4 configurations.
 *
 * All entries are Ed25519-signed; receipt JSON lives at
 * /public/receipts/convergence/<filename>.json (served from
 * /receipts/convergence/...). Verifier: /verify.
 *
 * To refresh: rerun the bench with CONVERGENCE_SIGNING_PRIVATE_KEY
 * set, copy results/published/convergence/*.json into
 * przm-web/public/receipts/convergence/, then update this file with
 * the new scores + receiptPaths.
 */
/** Pretty receipt URL = /receipts/<uuid>. Raw JSON download served
 *  from /receipts/convergence/<filename>.json as a static asset; the
 *  pretty page links there as 'Download JSON'. */
const PRETTY_RECEIPT_PREFIX = '/receipts'

export const CURRENT_SNAPSHOT: ConvergenceLeaderboardSnapshot = {
  benchmark: 'convergence-v0.1-preview',
  ranAt: '2026-05-17T19:32:06.087Z',
  configuration: { nAgents: 3, nRounds: 3 },
  fixtureCount: 30,
  entries: [
    {
      id: 'baseline-anthropic-claude-haiku-4-5',
      displayName: 'baseline / claude-haiku-4.5',
      orchestration: 'baseline',
      llmModel: 'claude-haiku-4-5',
      provider: 'anthropic',
      combined: {
        scores: {
          correct_final_answer_rate: 0.933,
          collapse_rate: 1.0,
          sycophancy_ratio: 0.033,
          tokens_per_correct_answer: 1173,
          position_flips_per_agent_per_round: 0.093,
        },
        fixtureCount: 30,
        durationSec: 393,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/5930d4db-c01d-40bb-ba6d-cc04cfea0360`,
      },
      holdout: {
        scores: {
          correct_final_answer_rate: 1.0,
          collapse_rate: 1.0,
          sycophancy_ratio: 0,
          tokens_per_correct_answer: 1185,
          position_flips_per_agent_per_round: 0.074,
        },
        fixtureCount: 6,
        durationSec: 79,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/e33a06d6-3ad7-4dde-be0a-23f613000ff3`,
      },
    },
    {
      id: 'baseline-azure-gpt-5-mini',
      displayName: 'baseline / gpt-5-mini',
      orchestration: 'baseline',
      llmModel: 'gpt-5-mini',
      provider: 'azure-openai',
      combined: {
        scores: {
          correct_final_answer_rate: 0.967,
          collapse_rate: 1.0,
          sycophancy_ratio: 0,
          tokens_per_correct_answer: 4987,
          position_flips_per_agent_per_round: 0.111,
        },
        fixtureCount: 30,
        durationSec: 2004,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/51a602ec-f23e-4bba-96ae-771e1cd212aa`,
      },
      holdout: {
        scores: {
          correct_final_answer_rate: 1.0,
          collapse_rate: 1.0,
          sycophancy_ratio: 0,
          tokens_per_correct_answer: 4766,
          position_flips_per_agent_per_round: 0.111,
        },
        fixtureCount: 6,
        durationSec: 409,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/e081746c-418d-4bc0-95d5-50a15b7be9c1`,
      },
    },
    {
      id: 'baseline-azure-gpt-4o-mini',
      displayName: 'baseline / gpt-4o-mini',
      orchestration: 'baseline',
      llmModel: 'gpt-4o-mini',
      provider: 'azure-openai',
      combined: {
        scores: {
          correct_final_answer_rate: 0.833,
          collapse_rate: 0.967,
          sycophancy_ratio: 0,
          tokens_per_correct_answer: 659,
          position_flips_per_agent_per_round: 0.122,
        },
        fixtureCount: 30,
        durationSec: 265,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/c9bfb562-e221-4884-9b69-a842dbd9ade2`,
      },
      holdout: {
        scores: {
          correct_final_answer_rate: 0.833,
          collapse_rate: 0.833,
          sycophancy_ratio: 0,
          tokens_per_correct_answer: 735,
          position_flips_per_agent_per_round: 0.093,
        },
        fixtureCount: 6,
        durationSec: 58,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/27c02406-fdb0-43d8-b3b1-59bce127afd8`,
      },
    },
    {
      id: 'autogen-azure-gpt-4o-mini',
      displayName: 'autogen / gpt-4o-mini',
      orchestration: 'autogen',
      llmModel: 'gpt-4o-mini',
      provider: 'azure-openai',
      combined: {
        scores: {
          correct_final_answer_rate: 0.833,
          collapse_rate: 0.133,
          sycophancy_ratio: 0,
          tokens_per_correct_answer: 875,
          position_flips_per_agent_per_round: 0.041,
        },
        fixtureCount: 30,
        durationSec: 407,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/2547fd35-a2fb-4551-a0fc-9e460117365d`,
      },
      holdout: {
        scores: {
          correct_final_answer_rate: 0.667,
          collapse_rate: 0,
          sycophancy_ratio: 0,
          tokens_per_correct_answer: 908,
          position_flips_per_agent_per_round: 0.018,
        },
        fixtureCount: 6,
        durationSec: 84,
        receiptPath: `${PRETTY_RECEIPT_PREFIX}/9893d90c-922a-4527-93c2-db54e094fb76`,
      },
    },
  ],
}

export function pctFormat(n: number): string {
  return (n * 100).toFixed(1) + '%'
}

export function numFormat(n: number): string {
  return n.toLocaleString(undefined, { maximumFractionDigits: 3 })
}

/**
 * The "primary" subset to display when showing one row per entry —
 * combined is preferred (largest fixture sample); falls back to seen
 * then holdout. Most entries have combined; later runs may have only
 * seen + holdout.
 */
export function primarySubset(entry: ConvergenceLeaderboardEntry): SubsetReceipt | undefined {
  return entry.combined ?? entry.seen ?? entry.holdout
}

/**
 * Holdout delta: holdout - primary, useful for surfacing
 * generalization gaps. Returns null if either subset is missing.
 */
export function holdoutDelta(
  entry: ConvergenceLeaderboardEntry,
): { correct: number; collapse: number; sycophancy: number } | null {
  const primary = primarySubset(entry)
  if (!primary || !entry.holdout) return null
  return {
    correct:
      entry.holdout.scores.correct_final_answer_rate -
      primary.scores.correct_final_answer_rate,
    collapse:
      entry.holdout.scores.collapse_rate - primary.scores.collapse_rate,
    sycophancy:
      entry.holdout.scores.sycophancy_ratio - primary.scores.sycophancy_ratio,
  }
}
