/**
 * Convergence leaderboard data — typed source-of-truth for the
 * /leaderboard page and the homepage teaser.
 *
 * v0.1: hand-curated from the most recent bench run while we wire up
 * the bench-to-web data pipe (sign + commit signed receipts → render).
 * When signed receipts are in results/published/convergence/, this
 * file can be regenerated by a script.
 */

export interface ConvergenceLeaderboardEntry {
  /** Stable id for keying + URLs. */
  id: string
  /** Display name: e.g. "baseline / claude-haiku-4.5". */
  displayName: string
  /** Framework / orchestration: baseline | autogen | crewai | langgraph. */
  orchestration: 'baseline' | 'autogen' | 'crewai' | 'langgraph' | 'openai-swarm'
  /** Underlying LLM. */
  llmModel: string
  /** Provider tag: anthropic | openai | azure | local. */
  provider: 'anthropic' | 'azure-openai' | 'openai' | 'local'
  /** All five scores. */
  scores: {
    correct_final_answer_rate: number
    collapse_rate: number
    sycophancy_ratio: number
    tokens_per_correct_answer: number
    position_flips_per_agent_per_round: number
  }
  /** Wall-clock seconds for the full fixture set. */
  durationSec: number
  /** Whether the receipt is signed + on the ledger. */
  signed: boolean
  /** Optional path to the signed receipt JSON. */
  receiptPath?: string
}

export interface ConvergenceLeaderboardSnapshot {
  benchmark: 'convergence-v0.1-preview'
  ranAt: string
  configuration: { nAgents: number; nRounds: number }
  fixtureCount: number
  entries: ConvergenceLeaderboardEntry[]
}

/**
 * Most recent run — 2026-05-17. 29 scenarios × 4 configurations.
 *
 * SIGNED column is currently false everywhere because we haven't
 * shipped the signed-receipt pipeline end-to-end yet (in flight).
 * When signed receipts are committed, flip `signed: true` and add
 * `receiptPath` per entry.
 */
export const CURRENT_SNAPSHOT: ConvergenceLeaderboardSnapshot = {
  benchmark: 'convergence-v0.1-preview',
  ranAt: '2026-05-17T16:54:58.425Z',
  configuration: { nAgents: 3, nRounds: 3 },
  fixtureCount: 29,
  entries: [
    {
      id: 'baseline-anthropic-claude-haiku-4-5',
      displayName: 'baseline / claude-haiku-4.5',
      orchestration: 'baseline',
      llmModel: 'claude-haiku-4-5',
      provider: 'anthropic',
      scores: {
        correct_final_answer_rate: 0.931,
        collapse_rate: 1.0,
        sycophancy_ratio: 0.035,
        tokens_per_correct_answer: 1178,
        position_flips_per_agent_per_round: 0.084,
      },
      durationSec: 393,
      signed: false,
    },
    {
      id: 'baseline-azure-gpt-5-mini',
      displayName: 'baseline / gpt-5-mini',
      orchestration: 'baseline',
      llmModel: 'gpt-5-mini',
      provider: 'azure-openai',
      scores: {
        correct_final_answer_rate: 0.965,
        collapse_rate: 1.0,
        sycophancy_ratio: 0,
        tokens_per_correct_answer: 4597,
        position_flips_per_agent_per_round: 0.107,
      },
      durationSec: 2004,
      signed: false,
    },
    {
      id: 'baseline-azure-gpt-4o-mini',
      displayName: 'baseline / gpt-4o-mini',
      orchestration: 'baseline',
      llmModel: 'gpt-4o-mini',
      provider: 'azure-openai',
      scores: {
        correct_final_answer_rate: 0.828,
        collapse_rate: 0.931,
        sycophancy_ratio: 0.069,
        tokens_per_correct_answer: 652,
        position_flips_per_agent_per_round: 0.115,
      },
      durationSec: 265,
      signed: false,
    },
    {
      id: 'autogen-azure-gpt-4o-mini',
      displayName: 'autogen / gpt-4o-mini',
      orchestration: 'autogen',
      llmModel: 'gpt-4o-mini',
      provider: 'azure-openai',
      scores: {
        correct_final_answer_rate: 0.828,
        collapse_rate: 0.172,
        sycophancy_ratio: 0.035,
        tokens_per_correct_answer: 938,
        position_flips_per_agent_per_round: 0.035,
      },
      durationSec: 407,
      signed: false,
    },
  ],
}

export function pctFormat(n: number): string {
  return (n * 100).toFixed(1) + '%'
}

export function numFormat(n: number): string {
  return n.toLocaleString(undefined, { maximumFractionDigits: 3 })
}
