/**
 * Convergence leaderboard data — typed source-of-truth for the
 * /leaderboard page and the homepage teaser.
 *
 * v0.1: hand-curated from the most recent bench run while we wire up
 * the bench-to-web data pipe (sign + commit signed receipts → render).
 * When signed receipts are in results/published/convergence/, this
 * file can be regenerated by a script.
 */

export interface ConvergenceLeaderboardEntry {
  /** Stable id for keying + URLs. */
  id: string
  /** Display name: e.g. "baseline / claude-haiku-4.5". */
  displayName: string
  /** Framework / orchestration: baseline | autogen | crewai | langgraph. */
  orchestration: 'baseline' | 'autogen' | 'crewai' | 'langgraph' | 'openai-swarm'
  /** Underlying LLM. */
  llmModel: string
  /** Provider tag: anthropic | openai | azure | local. */
  provider: 'anthropic' | 'azure-openai' | 'openai' | 'local'
  /** All five scores. */
  scores: {
    correct_final_answer_rate: number
    collapse_rate: number
    sycophancy_ratio: number
    tokens_per_correct_answer: number
    position_flips_per_agent_per_round: number
  }
  /** Wall-clock seconds for the full fixture set. */
  durationSec: number
  /** Whether the receipt is signed + on the ledger. */
  signed: boolean
  /** Optional path to the signed receipt JSON. */
  receiptPath?: string
}

export interface ConvergenceLeaderboardSnapshot {
  benchmark: 'convergence-v0.1-preview'
  ranAt: string
  configuration: { nAgents: number; nRounds: number }
  fixtureCount: number
  entries: ConvergenceLeaderboardEntry[]
}

/**
 * Most recent signed run — 2026-05-17T17:47Z. 30 scenarios × 4 configurations.
 *
 * All entries are Ed25519-signed; receipt JSON lives at
 * /public/receipts/convergence/<filename>.json (served from
 * /receipts/convergence/...). Verifier: /verify.
 *
 * To refresh: rerun the bench with CONVERGENCE_SIGNING_PRIVATE_KEY
 * set, copy results/published/convergence/*.json into
 * przm-web/public/receipts/convergence/, then update this file with
 * the new scores + receiptPaths.
 */
/** Pretty receipt URL = /receipts/<uuid>. Raw JSON download served
 *  from /receipts/convergence/<filename>.json as a static asset; the
 *  pretty page links there as 'Download JSON'. */
const PRETTY_RECEIPT_PREFIX = '/receipts'

export const CURRENT_SNAPSHOT: ConvergenceLeaderboardSnapshot = {
  benchmark: 'convergence-v0.1-preview',
  ranAt: '2026-05-17T17:47:28.102Z',
  configuration: { nAgents: 3, nRounds: 3 },
  fixtureCount: 30,
  entries: [
    {
      id: 'baseline-anthropic-claude-haiku-4-5',
      displayName: 'baseline / claude-haiku-4.5',
      orchestration: 'baseline',
      llmModel: 'claude-haiku-4-5',
      provider: 'anthropic',
      scores: {
        correct_final_answer_rate: 0.933,
        collapse_rate: 1.0,
        sycophancy_ratio: 0.033,
        tokens_per_correct_answer: 1173,
        position_flips_per_agent_per_round: 0.093,
      },
      durationSec: 393,
      signed: true,
      receiptPath: `${PRETTY_RECEIPT_PREFIX}/5930d4db-c01d-40bb-ba6d-cc04cfea0360`,
    },
    {
      id: 'baseline-azure-gpt-5-mini',
      displayName: 'baseline / gpt-5-mini',
      orchestration: 'baseline',
      llmModel: 'gpt-5-mini',
      provider: 'azure-openai',
      scores: {
        correct_final_answer_rate: 0.967,
        collapse_rate: 1.0,
        sycophancy_ratio: 0,
        tokens_per_correct_answer: 4987,
        position_flips_per_agent_per_round: 0.111,
      },
      durationSec: 2004,
      signed: true,
      receiptPath: `${PRETTY_RECEIPT_PREFIX}/51a602ec-f23e-4bba-96ae-771e1cd212aa`,
    },
    {
      id: 'baseline-azure-gpt-4o-mini',
      displayName: 'baseline / gpt-4o-mini',
      orchestration: 'baseline',
      llmModel: 'gpt-4o-mini',
      provider: 'azure-openai',
      scores: {
        correct_final_answer_rate: 0.833,
        collapse_rate: 0.967,
        sycophancy_ratio: 0,
        tokens_per_correct_answer: 659,
        position_flips_per_agent_per_round: 0.122,
      },
      durationSec: 265,
      signed: true,
      receiptPath: `${PRETTY_RECEIPT_PREFIX}/c9bfb562-e221-4884-9b69-a842dbd9ade2`,
    },
    {
      id: 'autogen-azure-gpt-4o-mini',
      displayName: 'autogen / gpt-4o-mini',
      orchestration: 'autogen',
      llmModel: 'gpt-4o-mini',
      provider: 'azure-openai',
      scores: {
        correct_final_answer_rate: 0.833,
        collapse_rate: 0.133,
        sycophancy_ratio: 0,
        tokens_per_correct_answer: 875,
        position_flips_per_agent_per_round: 0.041,
      },
      durationSec: 407,
      signed: true,
      receiptPath: `${PRETTY_RECEIPT_PREFIX}/2547fd35-a2fb-4551-a0fc-9e460117365d`,
    },
  ],
}

export function pctFormat(n: number): string {
  return (n * 100).toFixed(1) + '%'
}

export function numFormat(n: number): string {
  return n.toLocaleString(undefined, { maximumFractionDigits: 3 })
}
